apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}-jdbc
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
  ports:
  - name: ${project.artifactId}-jdbc
    port: 31000
    targetPort: 31000
  selector:
    app: ${project.artifactId}
